export const INJECT_TOKENS = {
  CHAT_MODEL: 'CHAT_MODEL',
  QUERY_USER_TOOL: 'QUERY_USER_TOOL',
  SEND_MAIL_TOOL: 'SEND_MAIL_TOOL',
  WEB_SEARCH_TOOL: 'WEB_SEARCH_TOOL',
  DB_USERS_CRUD_TOOL: 'DB_USERS_CRUD_TOOL',
  TIME_NOW_TOOL: 'TIME_NOW_TOOL',
  CRON_JOB_TOOL: 'CRON_JOB_TOOL',
};
